import { create } from 'zustand';
import { storage } from '../services/storage';

export interface Message {
  id: string;
  text: string;
  sender: 'user' | 'ai';
  timestamp: number;
  emotionAnalysis?: {
    labels: string[];
    keywords: string[];
    intensity: number;
    isNegativeEmotion?: boolean;
  };
}

export interface EmotionCard {
  id: string;
  text: string;
  type: 'label' | 'keyword';
  x: number;
  y: number;
  emotionType?: string; // 关联的情绪类型
}

export interface Connection {
  id: string;
  fromId: string;
  toId: string;
  reason?: string; // 连接原因
  isAutoGenerated?: boolean; // 是否 AI 自动生成
}

export interface ChatSession {
  id: string;
  title: string;
  messages: Message[];
  cards: EmotionCard[];
  connections: Connection[];
  timestamp: number;
  isSaved: boolean; // 是否已保存
  emotionFilter?: 'all' | 'negative' | 'positive'; // 情绪筛选
}

interface AppState {
  sessions: ChatSession[];
  currentSessionId: string | null;
  isHiddenMode: boolean;
  aiStyle: 'gentle' | 'concise';
  isAnimationEnabled: boolean;
  balloonCount: number;
  pendingSaveMessage: Message | null; // 待保存的消息
  
  // Getters
  getCurrentSession: () => ChatSession | null;
  getNegativeEmotionMessages: () => Message[];
  getFilteredMessages: () => Message[];
  
  // Actions
  createSession: (title?: string, isSaved?: boolean) => void;
  switchSession: (id: string) => void;
  deleteSession: (id: string) => void;
  addMessage: (text: string, sender: 'user' | 'ai', emotionAnalysis?: Message['emotionAnalysis']) => void;
  setPendingSaveMessage: (message: Message | null) => void;
  confirmSaveMessage: () => void;
  discardPendingMessage: () => void;
  toggleSessionSave: (sessionId: string) => void;
  setEmotionFilter: (filter: 'all' | 'negative' | 'positive') => void;
  addCards: (labels: string[], keywords: string[], emotionType?: string) => void;
  updateCardPosition: (id: string, x: number, y: number) => void;
  addConnection: (fromId: string, toId: string, reason?: string, isAutoGenerated?: boolean) => void;
  autoAddConnection: (fromId: string, toId: string, reason: string) => void;
  toggleHiddenMode: () => void;
  setAiStyle: (style: 'gentle' | 'concise') => void;
  setAnimationEnabled: (enabled: boolean) => void;
  setBalloonCount: (count: number) => void;
  clearAllData: () => void;
  loadState: () => void;
}

const DEFAULT_SESSION_TITLE = '新的情绪梳理';

export const useStore = create<AppState>((set, get) => ({
  sessions: [],
  currentSessionId: null,
  isHiddenMode: false,
  aiStyle: 'gentle',
  isAnimationEnabled: true,
  balloonCount: 5,
  pendingSaveMessage: null,

  getCurrentSession: () => {
    const { sessions, currentSessionId } = get();
    return sessions.find(s => s.id === currentSessionId) || null;
  },

  getNegativeEmotionMessages: () => {
    const session = get().getCurrentSession();
    if (!session) return [];
    return session.messages.filter(m => m.sender === 'user' && m.emotionAnalysis?.isNegativeEmotion);
  },

  getFilteredMessages: () => {
    const session = get().getCurrentSession();
    if (!session) return [];
    
    if (session.emotionFilter === 'negative') {
      return session.messages.filter(m => m.sender === 'user' && m.emotionAnalysis?.isNegativeEmotion);
    } else if (session.emotionFilter === 'positive') {
      return session.messages.filter(m => m.sender === 'user' && !m.emotionAnalysis?.isNegativeEmotion);
    }
    return session.messages;
  },

  createSession: (title = DEFAULT_SESSION_TITLE, isSaved = true) => {
    const newSession: ChatSession = {
      id: Math.random().toString(36).substr(2, 9),
      title,
      messages: [],
      cards: [],
      connections: [],
      timestamp: Date.now(),
      isSaved,
      emotionFilter: 'all'
    };
    set((state) => ({
      sessions: [newSession, ...state.sessions],
      currentSessionId: newSession.id,
    }));
    storage.save('mindbloom-sessions', get().sessions);
    storage.save('mindbloom-current-session-id', get().currentSessionId);
  },

  switchSession: (id) => {
    set({ currentSessionId: id });
    storage.save('mindbloom-current-session-id', id);
  },

  deleteSession: (id) => {
    set((state) => {
      const newSessions = state.sessions.filter(s => s.id !== id);
      let nextSessionId = state.currentSessionId;
      
      if (state.currentSessionId === id) {
        nextSessionId = newSessions.length > 0 ? newSessions[0].id : null;
      }
      
      return {
        sessions: newSessions,
        currentSessionId: nextSessionId,
      };
    });
    storage.save('mindbloom-sessions', get().sessions);
    storage.save('mindbloom-current-session-id', get().currentSessionId);
    
    if (get().sessions.length === 0) {
      get().createSession();
    }
  },

  addMessage: (text, sender, emotionAnalysis) => {
    const { currentSessionId, sessions } = get();
    if (!currentSessionId) return;

    const newMessage: Message = {
      id: Math.random().toString(36).substr(2, 9),
      text,
      sender,
      timestamp: Date.now(),
      emotionAnalysis
    };

    set((state) => ({
      sessions: state.sessions.map(s => {
        if (s.id === currentSessionId) {
          const newTitle = (s.messages.length === 0 && sender === 'user') 
            ? text.slice(0, 15) + (text.length > 15 ? '...' : '') 
            : s.title;
          return { ...s, title: newTitle, messages: [...s.messages, newMessage] };
        }
        return s;
      })
    }));
    storage.save('mindbloom-sessions', get().sessions);
  },

  setPendingSaveMessage: (message) => {
    set({ pendingSaveMessage: message });
  },

  confirmSaveMessage: () => {
    const { pendingSaveMessage } = get();
    if (pendingSaveMessage) {
      get().addMessage(pendingSaveMessage.text, pendingSaveMessage.sender, pendingSaveMessage.emotionAnalysis);
    }
    set({ pendingSaveMessage: null });
  },

  discardPendingMessage: () => {
    set({ pendingSaveMessage: null });
  },

  toggleSessionSave: (sessionId) => {
    set((state) => ({
      sessions: state.sessions.map(s => 
        s.id === sessionId ? { ...s, isSaved: !s.isSaved } : s
      )
    }));
    storage.save('mindbloom-sessions', get().sessions);
  },

  setEmotionFilter: (filter) => {
    const { currentSessionId } = get();
    if (!currentSessionId) return;
    
    set((state) => ({
      sessions: state.sessions.map(s => 
        s.id === currentSessionId ? { ...s, emotionFilter: filter } : s
      )
    }));
    storage.save('mindbloom-sessions', get().sessions);
  },

  addCards: (labels, keywords, emotionType) => {
    const { currentSessionId } = get();
    if (!currentSessionId) return;

    const newCards: EmotionCard[] = [];
    labels.forEach((label) => {
      newCards.push({
        id: Math.random().toString(36).substr(2, 9),
        text: label,
        type: 'label',
        x: Math.random() * 200 + 50,
        y: Math.random() * 200 + 50,
        emotionType
      });
    });

    keywords.forEach((keyword) => {
      newCards.push({
        id: Math.random().toString(36).substr(2, 9),
        text: keyword,
        type: 'keyword',
        x: Math.random() * 200 + 50,
        y: Math.random() * 200 + 50,
        emotionType
      });
    });

    set((state) => ({
      sessions: state.sessions.map(s => 
        s.id === currentSessionId ? { ...s, cards: [...s.cards, ...newCards] } : s
      )
    }));
    storage.save('mindbloom-sessions', get().sessions);
  },

  updateCardPosition: (id, x, y) => {
    const { currentSessionId } = get();
    if (!currentSessionId) return;

    set((state) => ({
      sessions: state.sessions.map(s => 
        s.id === currentSessionId 
          ? { ...s, cards: s.cards.map(c => c.id === id ? { ...c, x, y } : c) } 
          : s
      )
    }));
    storage.save('mindbloom-sessions', get().sessions);
  },

  addConnection: (fromId, toId, reason, isAutoGenerated = false) => {
    const { currentSessionId } = get();
    if (!currentSessionId) return;

    const newConnection: Connection = {
      id: Math.random().toString(36).substr(2, 9),
      fromId,
      toId,
      reason,
      isAutoGenerated
    };

    set((state) => ({
      sessions: state.sessions.map(s => 
        s.id === currentSessionId 
          ? { ...s, connections: [...s.connections, newConnection] } 
          : s
      )
    }));
    storage.save('mindbloom-sessions', get().sessions);
  },

  autoAddConnection: (fromId, toId, reason) => {
    get().addConnection(fromId, toId, reason, true);
  },

  toggleHiddenMode: () => {
    set((state) => ({ isHiddenMode: !state.isHiddenMode }));
    storage.save('mindbloom-settings', {
      isHiddenMode: get().isHiddenMode,
      aiStyle: get().aiStyle,
      isAnimationEnabled: get().isAnimationEnabled,
      balloonCount: get().balloonCount,
    });
  },

  setAiStyle: (aiStyle) => {
    set({ aiStyle });
    storage.save('mindbloom-settings', {
      isHiddenMode: get().isHiddenMode,
      aiStyle,
      isAnimationEnabled: get().isAnimationEnabled,
      balloonCount: get().balloonCount,
    });
  },

  setAnimationEnabled: (isAnimationEnabled) => {
    set({ isAnimationEnabled });
    storage.save('mindbloom-settings', {
      isHiddenMode: get().isHiddenMode,
      aiStyle: get().aiStyle,
      isAnimationEnabled,
      balloonCount: get().balloonCount,
    });
  },

  setBalloonCount: (balloonCount) => {
    set({ balloonCount });
    storage.save('mindbloom-settings', {
      isHiddenMode: get().isHiddenMode,
      aiStyle: get().aiStyle,
      isAnimationEnabled: get().isAnimationEnabled,
      balloonCount,
    });
  },

  clearAllData: () => {
    set({ sessions: [], currentSessionId: null, isHiddenMode: false, balloonCount: 5, pendingSaveMessage: null });
    storage.clear('mindbloom-sessions');
    storage.clear('mindbloom-current-session-id');
    storage.clear('mindbloom-settings');
    get().createSession();
  },

  loadState: () => {
    const sessions = storage.load('mindbloom-sessions') || [];
    const currentSessionId = storage.load('mindbloom-current-session-id');
    const settings = storage.load('mindbloom-settings') || {};

    set({
      sessions,
      currentSessionId,
      isHiddenMode: settings.isHiddenMode || false,
      aiStyle: settings.aiStyle || 'gentle',
      isAnimationEnabled: settings.isAnimationEnabled ?? true,
      balloonCount: settings.balloonCount || 5,
      pendingSaveMessage: null
    });

    if (get().sessions.length === 0) {
      get().createSession();
    }
  },
}));